# Generated by Django 5.1.5 on 2025-01-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
